name: Build and Push whisper Docker image to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'podman_images/whisper/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      working-directory: podman_images/whisper
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/whisper make push
